[tool.poetry]
name = "demisto-py"
version = "3.1.5"
description = "A Python library for the Demisto API"
authors = ["Demisto"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "demisto_client"}]
repository = "https://github.com/demisto/demisto-py"
keywords = ["Swagger", "Demisto API"]
classifiers=[
    'Natural Language :: English',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: Implementation :: CPython'
]
exclude = ["tests", "tests_data"]

[tool.poetry.dependencies]
python = "^3.8"
certifi = ">=2017.4.17"
six = ">=1.10"
python-dateutil = ">=2.5.3"
setuptools = ">=21.0.0"
urllib3 = ">=1.26.7"
tzlocal = "4.*"
importlib-metadata = "<4.3"
packaging = "^21.3"


[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
urllib3-mock = "^0.3.3"
requests = "^2.27.1"
mock = "^4.0.3"
flake8 = "^4.0.1"
pytest-mock = "^3.7.0"
mypy = "^0.942"
types-six = "^1.16.15"
types-tzlocal = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
