### =============================================================
### This configuration file is used by CircleCI build server
### https://circleci.com/docs/config-sample
### =============================================================
version: 2.1
parameters:
  python-orb-version:
    type: string
    default: "2.0.3"
  pythonversion:
    type: string
    default: "3.8"

orbs: 
  python: circleci/python@<< pipeline.parameters.python-orb-version >>

jobs:
  test:
    docker:
      - image: cimg/python:<< pipeline.parameters.pythonversion >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run pytest -v tests
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: verify
          command: |
            # Verify that code-gen.sh doesn't generate a diff
            bash -x ./gen-code.sh 
            # we diff only the code
            if git diff -- demisto_client; then
                echo "./gen-code.sh modified the source code. gen-code.sh should not modify the source code. If needed, run gen-code.sh before committing."
                echo "git diff -- demisto_client output:"
                echo "$DIFF_OUT"
                exit 1
            fi
            echo "All is good"
      - run: 
          name: build
          command: "poetry build --no-ansi"
      - run:
          name: deploy on tag change
          command: |
            if echo "${CIRCLE_TAG}" | grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$"
            then
              poetry publish -u __token__ -p "${PYPI_TOKEN}" --dry-run
            fi


workflows:
  version: 2
  build_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
